crosswalk:
  - property: alternative
    predicate: http://purl.org/dc/terms/alternative
    multiple: true
    function: 
  - property: tribal_title
    predicate: http://opaquenamespace.org/ns/tribalTitle
    multiple: true
    function: 
  - property: title
    predicate: http://purl.org/dc/terms/title
    multiple: true
    function: 
  - property: creator_attributes
    predicate: http://purl.org/dc/elements/1.1/creator
    multiple: true
    function: attributes_data
  - property: photographer_attributes
    predicate: http://id.loc.gov/vocabulary/relators/pht
    multiple: true
    function: attributes_data
  - property: arranger_attributes
    predicate: http://id.loc.gov/vocabulary/relators/arr
    multiple: true
    function: attributes_data
  - property: artist_attributes
    predicate: http://id.loc.gov/vocabulary/relators/art
    multiple: true
    function: attributes_data
  - property: author_attributes
    predicate: http://id.loc.gov/vocabulary/relators/aut
    multiple: true
    function: attributes_data
  - property: cartographer_attributes
    predicate: http://id.loc.gov/vocabulary/relators/ctg
    multiple: true
    function: attributes_data
  - property: collector_attributes
    predicate: http://id.loc.gov/vocabulary/relators/col
    multiple: true
    function: attributes_data
  - property: composer_attributes
    predicate: http://id.loc.gov/vocabulary/relators/cmp
    multiple: true
    function: attributes_data
  - property: creator_display
    predicate: http://opaquenamespace.org/ns/cco_creatorDisplay
    multiple: true
    function: 
  - property: contributor_attributes
    predicate: http://purl.org/dc/elements/1.1/contributor
    multiple: true
    function: attributes_data
  - property: dedicatee_attributes
    predicate: http://id.loc.gov/vocabulary/relators/dte
    multiple: true
    function: attributes_data
  - property: designer_attributes
    predicate: http://id.loc.gov/vocabulary/relators/dsr
    multiple: true
    function: attributes_data
  - property: donor_attributes
    predicate: http://id.loc.gov/vocabulary/relators/dnr
    multiple: true
    function: attributes_data
  - property: editor_attributes
    predicate: http://id.loc.gov/vocabulary/relators/edt
    multiple: true
    function: attributes_data
  - property: illustrator_attributes
    predicate: http://id.loc.gov/vocabulary/relators/ill
    multiple: true
    function: attributes_data
  - property: interviewee_attributes
    predicate: http://id.loc.gov/vocabulary/relators/ive
    multiple: true
    function: attributes_data
  - property: interviewer_attributes
    predicate: http://id.loc.gov/vocabulary/relators/ivr
    multiple: true
    function: attributes_data
  - property: landscape_architect_attributes
    predicate: http://id.loc.gov/vocabulary/relators/lsa
    multiple: true
    function: attributes_data
  - property: lyricist_attributes
    predicate: http://id.loc.gov/vocabulary/relators/lyr
    multiple: true
    function: attributes_data
  - property: owner_attributes
    predicate: http://id.loc.gov/vocabulary/relators/own
    multiple: true
    function: attributes_data
  - property: patron_attributes
    predicate: http://id.loc.gov/vocabulary/relators/pat
    multiple: true
    function: attributes_data
  - property: print_maker_attributes
    predicate: http://id.loc.gov/vocabulary/relators/prm
    multiple: true
    function: attributes_data
  - property: recipient_attributes
    predicate: http://id.loc.gov/vocabulary/relators/rcp
    multiple: true
    function: attributes_data
  - property: transcriber_attributes
    predicate: http://id.loc.gov/vocabulary/relators/trc
    multiple: true
    function: attributes_data
  - property: translator_attributes
    predicate: http://id.loc.gov/vocabulary/relators/trl
    multiple: true
    function: attributes_data
  - property: description
    predicate: http://purl.org/dc/terms/description
    multiple: true
    function: 
  - property: abstract
    predicate: http://purl.org/dc/terms/abstract
    multiple: true
    function: 
  - property: biographical_information
    predicate: http://rdaregistry.info/Elements/a/P50113
    multiple: true
    function: 
  - property: compass_direction
    predicate: http://opaquenamespace.org/ns/compassDirection
    multiple: true
    function: 
  - property: cover_description
    predicate: http://opaquenamespace.org/ns/coverDescription
    multiple: true
    function: 
  - property: coverage
    predicate: http://purl.org/dc/elements/1.1/coverage
    multiple: true
    function: 
  - property: description_of_manifestation
    predicate: http://rdaregistry.info/Elements/w/P10271
    multiple: true
    function: 
  - property: designer_inscription
    predicate: http://opaquenamespace.org/ns/cdwa/InscriptionTranscription
    multiple: true
    function: 
  - property: first_line
    predicate: http://opaquenamespace.org/ns/sheetmusic_firstLine
    multiple: false
    function: 
  - property: first_line_chorus
    predicate: http://opaquenamespace.org/ns/sheetmusic_firstLineChorus
    multiple: false
    function: 
  - property: form_of_work_attributes
    predicate: http://rdaregistry.info/Elements/w/P10004
    multiple: true
    function: attributes_data
  - property: former_owner
    predicate: http://id.loc.gov/vocabulary/relators/fmo
    multiple: true
    function: 
  - property: inscription
    predicate: http://purl.org/vra/hasInscription
    multiple: true
    function: 
  - property: instrumentation
    predicate: http://opaquenamespace.org/ns/sheetmusic_instrumentation
    multiple: true
    function: 
  - property: layout
    predicate: http://rdaregistry.info/Elements/m/P30155
    multiple: true
    function: 
  - property: military_highest_rank
    predicate: http://opaquenamespace.org/ns/militaryHighestRank
    multiple: false
    function: 
  - property: military_occupation
    predicate: http://opaquenamespace.org/ns/militaryOccupation
    multiple: true
    function: 
  - property: military_service_location
    predicate: http://opaquenamespace.org/ns/militaryServiceLocation
    multiple: true
    function: 
  - property: mode_of_issuance
    predicate: http://rdaregistry.info/Elements/m/P30003
    multiple: true
    function: 
  - property: mods_note
    predicate: http://www.loc.gov/standards/mods/modsrdf/v1/#note
    multiple: true
    function: 
  - property: motif
    predicate: http://opaquenamespace.org/ns/motif
    multiple: true
    function: 
  - property: object_orientation
    predicate: http://opaquenamespace.org/ns/objectOrientation
    multiple: false
    function: 
  - property: photograph_orientation
    predicate: http://opaquenamespace.org/ns/photographOrientation
    multiple: false
    function: 
  - property: tribal_notes
    predicate: http://opaquenamespace.org/ns/tribalNotes
    multiple: true
    function: 
  - property: source_condition
    predicate: http://opaquenamespace.org/ns/sourceCondition
    multiple: true
    function: 
  - property: table_of_contents
    predicate: http://purl.org/dc/terms/tableOfContents
    multiple: true
    function: 
  - property: temporal
    predicate: http://purl.org/dc/terms/temporal
    multiple: true
    function: 
  - property: view
    predicate: http://opaquenamespace.org/ns/cco_viewDescription
    multiple: true
    function: 
  - property: subject_attributes
    predicate: http://purl.org/dc/terms/subject
    multiple: true
    function: attributes_data
  - property: award
    predicate: http://schema.org/award
    multiple: true
    function: 
  - property: cultural_context_attributes
    predicate: http://purl.org/vra/hasCulture
    multiple: true
    function: attributes_data
  - property: ethnographic_term_attributes
    predicate: http://opaquenamespace.org/ns/ethnographic
    multiple: true
    function: attributes_data
  - property: event
    predicate: http://schema.org/event
    multiple: true
    function: 
  - property: keyword
    predicate: http://purl.org/dc/elements/1.1/subject
    multiple: true
    function: 
  - property: legal_name
    predicate: http://schema.org/legalName
    multiple: true
    function: 
  - property: military_branch_attributes
    predicate: http://opaquenamespace.org/ns/militaryBranch
    multiple: true
    function: attributes_data
  - property: sports_team
    predicate: http://opaquenamespace.org/ns/sportsTeam
    multiple: true
    function: 
  - property: state_or_edition
    predicate: http://opaquenamespace.org/ns/vra_stateEdition
    multiple: true
    function: 
  - property: style_or_period_attributes
    predicate: http://purl.org/vra/hasStylePeriod
    multiple: true
    function: attributes_data
  - property: tribal_classes
    predicate: http://opaquenamespace.org/ns/tribalClasses
    multiple: true
    function: 
  - property: tribal_terms
    predicate: http://opaquenamespace.org/ns/tribalTerms
    multiple: true
    function: 
  - property: phylum_or_division_attributes
    predicate: http://rs.tdwg.org/dwc/terms/phylum
    multiple: true
    function: attributes_data
  - property: taxon_class_attributes
    predicate: http://rs.tdwg.org/dwc/terms/class
    multiple: true
    function: attributes_data
  - property: order_attributes
    predicate: http://rs.tdwg.org/dwc/terms/order
    multiple: true
    function: attributes_data
  - property: family_attributes
    predicate: http://rs.tdwg.org/dwc/terms/family
    multiple: true
    function: attributes_data
  - property: genus_attributes
    predicate: http://rs.tdwg.org/dwc/terms/genus
    multiple: true
    function: attributes_data
  - property: species_attributes
    predicate: http://rs.tdwg.org/dwc/terms/specificEpithet
    multiple: true
    function: attributes_data
  - property: common_name_attributes
    predicate: http://rs.tdwg.org/dwc/terms/vernacularName
    multiple: true
    function: attributes_data
  - property: accepted_name_usage
    predicate: http://rs.tdwg.org/dwc/terms/acceptedNameUsage
    multiple: true
    function: 
  - property: original_name_usage
    predicate: http://rs.tdwg.org/dwc/terms/originalNameUsage
    multiple: true
    function: 
  - property: scientific_name_authorship
    predicate: http://rs.tdwg.org/dwc/terms/scientificNameAuthorship
    multiple: true
    function: 
  - property: specimen_type
    predicate: http://opaquenamespace.org/ns/specimenType
    multiple: false
    function: 
  - property: identification_verification_status
    predicate: http://rs.tdwg.org/dwc/terms/identificationVerificationStatus
    multiple: false
    function: 
  - property: location_attributes
    predicate: http://purl.org/dc/terms/spatial
    multiple: true
    function: attributes_data
  - property: box
    predicate: http://schema.org/box
    multiple: true
    function: 
  - property: gps_latitude
    predicate: http://www.w3.org/2003/12/exif/ns#gpsLatitude
    multiple: false
    function: 
  - property: gps_longitude
    predicate: http://www.w3.org/2003/12/exif/ns#gpsLongitude
    multiple: false
    function: 
  - property: ranger_district_attributes
    predicate: http://opaquenamespace.org/ns/rangerDistrict
    multiple: true
    function: attributes_data
  - property: street_address
    predicate: http://www.loc.gov/mads/rdf/v1#streetAddress
    multiple: true
    function: 
  - property: tgn_attributes
    predicate: http://dbpedia.org/ontology/HistoricPlace
    multiple: true
    function: attributes_data
  - property: water_basin_attributes
    predicate: http://opaquenamespace.org/ns/waterBasin
    multiple: true
    function: attributes_data
  - property: date
    predicate: http://purl.org/dc/terms/date
    multiple: true
    function: 
  - property: acquisition_date
    predicate: http://opaquenamespace.org/ns/acquisitionDate
    multiple: true
    function: 
  - property: award_date
    predicate: http://opaquenamespace.org/ns/awardDate
    multiple: true
    function: 
  - property: collected_date
    predicate: http://opaquenamespace.org/ns/collectedDate
    multiple: true
    function: 
  - property: date_created
    predicate: http://purl.org/dc/terms/created
    multiple: true
    function: 
  - property: issued
    predicate: http://purl.org/dc/terms/issued
    multiple: true
    function: 
  - property: view_date
    predicate: http://opaquenamespace.org/ns/cco_viewDate
    multiple: true
    function: 
  - property: accession_number
    predicate: http://opaquenamespace.org/ns/cco_accessionNumber
    multiple: true
    function: 
  - property: barcode
    predicate: http://id.loc.gov/ontologies/bibframe/Barcode
    multiple: true
    function: 
  - property: hydrologic_unit_code
    predicate: http://opaquenamespace.org/ns/hydrologicUnitCode
    multiple: true
    function: 
  - property: identifier
    predicate: http://purl.org/dc/terms/identifier
    multiple: true
    function: 
  - property: item_locator
    predicate: http://purl.org/ontology/holding#label
    multiple: true
    function: 
  - property: longitude_latitude_identification
    predicate: http://opaquenamespace.org/ns/llid
    multiple: true
    function: 
  - property: license
    predicate: http://purl.org/dc/terms/rights
    multiple: false
    function: 
  - property: access_restrictions_attributes
    predicate: http://purl.org/dc/terms/accessRights
    multiple: false
    function: attributes_data
  - property: copyright_claimant
    predicate: http://id.loc.gov/vocabulary/relators/cpc
    multiple: true
    function: 
  - property: rights_holder
    predicate: http://purl.org/dc/terms/rightsHolder
    multiple: true
    function: 
  - property: rights_note
    predicate: http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#rightsExpression
    multiple: true
    function: 
  - property: rights_statement
    predicate: http://www.europeana.edu/schemas/edm/rights
    multiple: false
    function: 
  - property: use_restrictions
    predicate: http://rdaregistry.info/Elements/u/P60497
    multiple: true
    function: 
  - property: repository_attributes
    predicate: http://id.loc.gov/vocabulary/relators/rps
    multiple: false
    function: attributes_data
  - property: copy_location
    predicate: http://www.loc.gov/standards/mods/modsrdf/v1/#locationCopySublocation
    multiple: true
    function: 
  - property: location_copyshelf_location
    predicate: http://www.loc.gov/standards/mods/modsrdf/v1/#locationCopyShelfLocator
    multiple: true
    function: 
  - property: local_collection_name_attributes
    predicate: http://opaquenamespace.org/ns/localCollectionName
    multiple: true
    function: attributes_data
  - property: box_number
    predicate: http://opaquenamespace.org/ns/boxNumber
    multiple: true
    function: 
  - property: citation
    predicate: http://schema.org/citation
    multiple: true
    function: 
  - property: contained_in_journal
    predicate: http://purl.org/net/nknouf/ns/bibtex#hasJournal
    multiple: true
    function: 
  - property: current_repository_id
    predicate: http://opaquenamespace.org/ns/vra_idCurrentRepository
    multiple: true
    function: 
  - property: folder_name
    predicate: http://opaquenamespace.org/ns/folderName
    multiple: true
    function: 
  - property: folder_number
    predicate: http://opaquenamespace.org/ns/folderNumber
    multiple: true
    function: 
  - property: has_number
    predicate: http://purl.org/net/nknouf/ns/bibtex#hasNumber
    multiple: true
    function: 
  - property: is_volume
    predicate: http://purl.org/net/nknouf/ns/bibtex#hasVolume
    multiple: true
    function: 
  - property: language
    predicate: http://purl.org/dc/terms/language
    multiple: true
    function: 
  - property: local_collection_id
    predicate: http://opaquenamespace.org/ns/localCollectionID
    multiple: true
    function: 
  - property: on_pages
    predicate: http://purl.org/net/nknouf/ns/bibtex#hasPages
    multiple: true
    function: 
  - property: publisher_attributes
    predicate: http://purl.org/dc/terms/publisher
    multiple: true
    function: attributes_data
  - property: place_of_production_attributes
    predicate: http://rdaregistry.info/Elements/u/P60161
    multiple: true
    function: attributes_data
  - property: provenance
    predicate: http://purl.org/dc/terms/provenance
    multiple: true
    function: 
  - property: publication_place_attributes
    predicate: http://id.loc.gov/vocabulary/relators/pup
    multiple: true
    function: attributes_data
  - property: series_name
    predicate: http://opaquenamespace.org/ns/seriesName
    multiple: true
    function: 
  - property: series_number
    predicate: http://opaquenamespace.org/ns/seriesNumber
    multiple: true
    function: 
  - property: source
    predicate: http://purl.org/dc/terms/source
    multiple: true
    function: 
  - property: art_series
    predicate: http://opaquenamespace.org/ns/artSeries
    multiple: true
    function: 
  - property: has_finding_aid
    predicate: http://lod.xdams.org/reload/oad/has_findingAid
    multiple: true
    function: 
  - property: has_part
    predicate: http://purl.org/dc/terms/hasPart
    multiple: true
    function: 
  - property: has_version
    predicate: http://purl.org/dc/terms/hasVersion
    multiple: true
    function: 
  - property: is_part_of
    predicate: http://purl.org/dc/terms/isPartOf
    multiple: true
    function: 
  - property: is_version_of
    predicate: http://purl.org/dc/terms/isVersionOf
    multiple: true
    function: 
  - property: larger_work
    predicate: http://opaquenamespace.org/ns/sheetmusic_largerWork
    multiple: true
    function: 
  - property: relation
    predicate: http://purl.org/dc/terms/relation
    multiple: true
    function: 
  - property: related_url
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
    multiple: true
    function: 
  - property: resource_type
    predicate: http://purl.org/dc/terms/type
    multiple: false
    function: 
  - property: workType_attributes
    predicate: http://rdaregistry.info/Elements/w/P10004
    multiple: true
    function: attributes_data
  - property: material
    predicate: http://purl.org/vra/material
    multiple: true
    function: 
  - property: measurements
    predicate: http://opaquenamespace.org/ns/vra_measurements
    multiple: true
    function: 
  - property: physical_extent
    predicate: http://www.loc.gov/standards/mods/modsrdf/v1/#physicalExtent
    multiple: true
    function: 
  - property: technique
    predicate: http://purl.org/vra/hasTechnique
    multiple: true
    function: 
  - property: color_content
    predicate: http://rdaregistry.info/Elements/e/P20224
    multiple: true
    function: 
  - property: conversion
    predicate: http://opaquenamespace.org/ns/conversionSpecifications
    multiple: true
    function: 
  - property: full_text
    predicate: http://opaquenamespace.org/ns/fullText
    multiple: false
    function: 
  - property: exhibit
    predicate: http://opaquenamespace.org/ns/exhibit
    multiple: true
    function: 
  - property: institution_attributes
    predicate: http://opaquenamespace.org/ns/contributingInstitution
    multiple: true
    function: attributes_data
  - property: original_filename
    predicate: http://www.loc.gov/premis/rdf/v3/originalName
    multiple: false
    function: 
  - property: replaces_url
    predicate: http://purl.org/dc/terms/replaces
    multiple: false
    function: 
  - property: resolution
    predicate: http://www.w3.org/2003/12/exif/ns#resolution
    multiple: false
    function: 
  - property: full_size_download_allowed
    predicate: http://opaquenamespace.org/ns/fullSizeDownloadAllowed
    multiple: false
    function: 
  - property: date_modified
    predicate: http://purl.org/dc/terms/modified
    multiple: false
    function: 
  - property: date_uploaded
    predicate: http://purl.org/dc/terms/dateSubmitted
    multiple: false
    function:
