fields:
  title:	title
  alternative:	alternative
  captionTitle:	
  tribalTitle:	tribal_title
  creator:	creator
  contributor:	contributor
  arranger:	arranger
  artist:	artist
  author:	author
  cartographer:	cartographer
  composer:	composer
  donor:	donor
  illustrator:	illustrator
  interviewee:	interviewee
  interviewer:	interviewer
  lyricist:	lyricist
  photographer:	photographer
  printMaker:	print_maker
  scribe:	scribe
  transcriber:	transcriber
  translator:	translator
  creatorDisplay:	creator_display
  collector:	collector
  designer:	designer
  dedicatee:	dedicatee
  recipient:	recipient
  owner:	owner
  formerOwner:	former_owner
  description:	description
  abstract:	abstract
  inscription:	inscription
  view:	view
  firstLine:	first_line
  firstLineChorus:	first_line_chorus
  compassDirection:	compass_direction
  objectOrientation:	object_orientation
  photographOrientation:	photograph_orientation
  conditionOfSource:	source_condition
  instrumentation:	instrumentation
  od_content:	od_content
  militaryServiceLocation:	military_service_location
  militaryHighestRank:	military_highest_rank
  militaryOccupation:	military_occupation
  cover:	cover
  canzonierePoems:	canzoniere_poems
  coverage:	coverage
  provenance:	provenance
  tableOfContents:	table_of_contents
  tribalNotes:	tribal_notes
  acceptedNameUsage:	accepted_name_usage
  originalNameUsage:	original_name_usage
  specimenType:	specimen_type
  temporal:	temporal
  designerLabel:	designer_label
  motif:	motif
  lcsubject:	subject
  subject:	keyword
  stateEdition:	state_or_edition
  stylePeriod:	style_or_period
  workType:	workType
  militaryBranch:	military_branch
  ethnographicTerm:	ethnographic_term
  sportsTeam:	sports_team
  tribalClasses:	tribal_classes
  tribalTerms:	tribal_terms
  award:	award
  legalName:	legal_name
  geobox:	geobox
  latitude: gps_latitude
  longitude:    gps_longitude
  location:	location
  streetAddress:	street_address
  rangerDistrict:	ranger_district
  waterBasin:	water_basin
  tgn:	tgn
  date:	date
  earliestDate:	
  issued:	issued
  latestDate:	
  viewDate:	view_date
  awardDate:	award_date
  collectedDate:	collected_date
  acquisitionDate:	acquisition_date
  identifier:	identifier
  itemLocator:	item_locator
  accessionNumber:	accession_number
  lccn:	
  barcode:	barcode
  hydrologicUnitCode:	hydrologic_unit_code
  llid:	llid
  rights:	rights_statement
  rightsHolder:	rights_holder
  dcRightsHolder:	dc_rights_holder
  useRestrictions:	use_restrictions
  accessRestrictions:	access_restrictions
  license:	license
  copyrightClaimant:	copyright_claimant
  source:	source
  language:	language
  publisher:	publisher
  placeOfPublication:	publication_place
  od_repository:	repository
  localCollectionID:	local_collection_id
  localCollectionName:	local_collection_name
  seriesName:	series_name
  seriesNumber:	series_number
  boxNumber:	box_number
  folderNumber:	folder_number
  folderName:	folder_name
  type:	type
  format:	format
  physicalExtent:	physical_extent
  extent:	extent
  measurements:	measurements
  material:	material
  support:	
  technique:	technique
  set:	
  primarySet:	
  relation:	relation
  largerWork:	larger_work
  artSeries:	art_series
  hostItem:	host_item
  hasPart:	has_part
  isPartOf:	is_part_of
  hasVersion:	has_version
  isVersionOf:	is_version_of
  findingAid:	has_finding_aid
  institution:	institution
  conversion:	conversion
  dateDigitized:	date_digitized
  created:	created
  modified:	modified
  exhibit:	exhibit
  fullText:	
  tribalStatus:	
  submissionDate:	submission_date
  replacesUrl:	replaces_url
  citation:	citation
  editor:	editor
  numberOfPages:	number_of_pages
  event:	event
  phylum:	phylum_or_division
  taxonClass:	taxon_class
  order:	order
  family:	family
  genus:	genus
  species:	species
  commonNames:	common_names
  scientificNameAuthorship:	scientific_name_authorship
  higherClassification:	higher_classification
  identificationVerificationStatus:	identification_verification_status
  preservation:	preservation
  hasFixity:	has_fixity
  locationCopySublocation:	location_copy_sublocation
  locationCopyShelfLocator:	location_copy_shelf_locator
  note:	note
  culturalContext:	cultural_context
  idCurrentRepository:	id_current_repository
  imageWidth:	width
  imageHeight:	height
  imageResolution:	resolution
  imageOrientation:	orientation
  colorSpace:	color_space
  formOfWork:	form_of_work
  fileSize:	file_size
  layout:	layout
  containedInManifestation:	contained_in_manifestation
  modeOfIssuance:	mode_of_issuance
  placeOfProduction:	place_of_production
  descriptionOfManifestation:	description_of_manifestation
  colourContent:	colour_content
  biographicalInformation:	biographical_information
  containedInJournal:	contained_in_journal
  isVolume:	is_volume
  hasNumber:	has_number
  onPages:	on_pages
