fields:
  alternative: alternative
  tribalTitle: tribal_title
  title: title
  creator: creator
  photographer: photographer
  arranger: arranger
  artist: artist
  author: author
  cartographer: cartographer
  collector: collector
  composer: composer
  creatorDisplay: creator_display
  contributor: contributor
  dedicatee: dedicatee
  designer: designer
  donor: donor
  editor: editor
  illustrator: illustrator
  interviewee: interviewee
  interviewer: interviewer
  lyricist: lyricist
  owner: owner
  printMaker: print_maker
  recipient: recipient
  transcriber: transcriber
  translator: translator
  landscapeArchitect: landscape_architect
  description: description
  abstract: abstract
  biographicalInformation: biographical_information
  compassDirection: compass_direction
  cover: cover_description
  coverage: coverage
  descriptionOfManifestation: description_of_manifestation
  designerLabel: designer_inscription
  firstLine: first_line
  firstLineChorus: first_line_chorus
  formOfWork: form_of_work
  formerOwner: former_owner
  inscription: inscription
  instrumentation: instrumentation
  layout: layout
  militaryHighestRank: military_highest_rank
  militaryOccupation: military_occupation
  militaryServiceLocation: military_service_location
  modeOfIssuance: mode_of_issuance
  note: mods_note
  motif: motif
  objectOrientation: object_orientation
  photographOrientation: photograph_orientation
  tribalNotes: tribal_notes
  conditionOfSource: source_condition
  tableOfContents: table_of_contents
  temporal: temporal
  view: view
  lcsubject: subject
  award: award
  culturalContext: cultural_context
  ethnographicTerm: ethnographic_term
  event: event
  subject: keyword
  legalName: legal_name
  militaryBranch: military_branch
  sportsTeam: sports_team
  stateEdition: state_or_edition
  stylePeriod: style_or_period
  tribalClasses: tribal_classes
  tribalTerms: tribal_terms
  phylum: phylum_or_division
  taxonClass: taxon_class
  order: order
  family: family
  genus: genus
  species: species
  commonNames: common_name
  acceptedNameUsage: accepted_name_usage
  originalNameUsage: original_name_usage
  scientificNameAuthorship: scientific_name_authorship
  specimenType: specimen_type
  identificationVerificationStatus: identification_verification_status
  location: location
  geobox: box
  latitude: gps_latitude
  longitude: gps_longitude
  rangerDistrict: ranger_district
  streetAddress: street_address
  tgn: tgn
  waterBasin: water_basin
  date: date
  acquisitionDate: acquisition_date
  awardDate: award_date
  collectedDate: collected_date
  created: date_created
  issued: issued
  viewDate: view_date
  accessionNumber: accession_number
  barcode: barcode
  hydrologicUnitCode: hydrologic_unit_code
  identifier: identifier
  itemLocator: item_locator
  llid: longitude_latitude_identification
  license: license
  accessRestrictions: access_restrictions
  copyrightClaimant: copyright_claimant
  dcRightsHolder: rights_holder
  rights: rights_statement
  useRestrictions: use_restrictions
  od_repository: repository
  locationCopySublocation: copy_location
  locationCopyShelfLocator: location_copyshelf_location
  localCollectionName: local_collection_name
  boxNumber: box_number
  citation: citation
  containedInJournal: contained_in_journal
  idCurrentRepository: current_repository_id
  folderName: folder_name
  folderNumber: folder_number
  hasNumber: has_number
  isVolume: is_volume
  language: language
  localCollectionID: local_collection_id
  onPages: on_pages
  publisher: publisher
  placeOfProduction: place_of_production
  provenance: provenance
  placeOfPublication: publication_place
  seriesName: series_name
  seriesNumber: series_number
  source: source
  artSeries: art_series
  findingAid: has_finding_aid
  hasPart: has_part
  hasVersion: has_version
  isPartOf: is_part_of
  isVersionOf: is_version_of
  largerWork: larger_work
  relation: relation
  type: resource_type
  workType: workType
  material: material
  measurements: measurements
  extent: measurements
  physicalExtent: physical_extent
  technique: technique
  colourContent: color_content
  conversion: conversion
  fullText: full_text
  exhibit: exhibit
  institution: institution
  replacesUrl: replaces_url
  imageResolution: resolution
